on: 
  push:
    branches: 
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: http://185.211.7.218
        username: u237653964
        password: Ftp@gabriel1
        server-dir: public_html/spacelingo_web/
        port: 21
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
